application: examen-hadesth
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: examen.app

- url: /index\.html
  script: examen.app

- url: /register\.html
  script: examen.app

- url: /user_index\.html
  script: examen.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
